services:
  - type: web
    name: authentik-server
    dockerCompose: docker-compose.yml
    service: server
    env: docker
    healthCheckPath: /-/health/
    
  - type: worker
    name: authentik-worker
    dockerCompose: docker-compose.yml
    service: worker
    env: docker
